import './form/inputtype/checkbox/Checkbox';
import './form/inputtype/combobox/ComboBox';
import './form/inputtype/time/Date';
import './form/inputtype/time/DateTime';
import './form/inputtype/time/DateTimeRange';
import './form/inputtype/time/Time';
import './form/inputtype/number/Double';
import './form/inputtype/number/Long';
import './form/inputtype/geo/GeoPoint';
import './form/inputtype/support/NoInputTypeFoundView';
import './form/inputtype/principal/PrincipalSelector';
import './form/inputtype/radiobutton/RadioButton';
import './form/inputtype/text/TextArea';
import './form/inputtype/text/TextLine';
// import './fineuploader/fine-uploader.min.js';
// import './jquery-3.4.1.min.js';
// import './jquery-ui.min.js';
// import './jquery.simulate.js';
// import './codemirror/codemirror.js';
// import './codemirror/addon/loadmode.js';
// import './signals.js';
// import './hasher.js';
// import './crossroads.js';
// import './slickgrid/lib/jquery.event.drag-2.3.js';
// import './slickgrid/lib/jquery.event.drop-2.3.js';
// import './slickgrid/slick.core.js';
// import './slickgrid/slick.grid.js';
// import './slickgrid/slick.dataview.js';
// import './slickgrid/slick.remotemodel.js';
// import './slickgrid/slick.rowselectionmodel.js';
// import './slickgrid/slick.checkboxselectcolumn.js';
// import './slickgrid/slick.rowmovemanager.js';
// import './mousetrap.js';
// import './mousetrap-global-bind.min.js';
// import './q.js';
// import './noconflict.js';
