// Re-exported from @enonic/input-types: the input types live in the toolkit now (#4692).

export type {
    Alignment,
    CheckboxConfig,
    ComboBoxConfig,
    DateConfig,
    DateTimeConfig,
    DateTimeRangeConfig,
    FieldSetValidationNode,
    FormValidationNode,
    FormValidationResult,
    GeoPointConfig,
    InputTypeConfig,
    InputTypeDescriptor,
    InputValidationNode,
    InstantConfig,
    ItemSetValidationNode,
    NumberConfig,
    OccurrenceManagerState,
    OccurrenceValidationState,
    OptionConfig,
    OptionSetValidationNode,
    PrincipalSelectorConfig,
    RadioButtonConfig,
    RawValueMap,
    ResolvePhrase,
    ServerError,
    SetOccurrenceManagerState,
    SkippedValidationNode,
    TextAreaConfig,
    TextLineConfig,
    TimeConfig,
    ValidateFormOptions,
    ValidationMessage,
    ValidationResult,
} from '@enonic/input-types';
export {
    CheckboxDescriptor,
    ComboBoxDescriptor,
    DateDescriptor,
    DateTimeDescriptor,
    DateTimeRangeDescriptor,
    DoubleDescriptor,
    GeoPointDescriptor,
    getEffectiveOccurrences,
    InstantDescriptor,
    invalidValue,
    LongDescriptor,
    OccurrenceManager,
    PrincipalSelectorDescriptor,
    RadioButtonDescriptor,
    readOptions,
    resolveValidationMessage,
    SetOccurrenceManager,
    TagDescriptor,
    TextAreaDescriptor,
    TextLineDescriptor,
    TimeDescriptor,
    validateForm,
    validateFormItemsValid,
} from '@enonic/input-types';
