name: Gradle Build

on:
  push:

concurrency: build-${{ github.ref }}

jobs:
  publish_vars:
    runs-on: ubuntu-latest

    outputs:
      publish: ${{ steps.publish_vars.outputs.release != 'true' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/4.') || github.ref == 'refs/heads/issue-3908') }}
      repo: ${{ steps.publish_vars.outputs.repo }}

    steps:

      - uses: actions/checkout@v4

      - name: Get publishing variables
        id: publish_vars
        uses: enonic/release-tools/publish-vars@master
        env:
          PROPERTIES_PATH: './gradle.properties'

  build:
    runs-on: ubuntu-latest

    needs: publish_vars

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Prepare Gradle Arguments
        run: |
          BASE_ARGS="--refresh-dependencies build"
          PUBLISH_ARGS="publish -Pcom.enonic.xp.app.production=true -PrepoKey=${{ needs.publish_vars.outputs.repo }} -PrepoUser=ci -PrepoPassword=${{ secrets.ARTIFACTORY_PASSWORD }}"
          if [ "${{ needs.publish_vars.outputs.publish }}" == "true" ]; then
            GRADLE_ARGS="$BASE_ARGS $PUBLISH_ARGS"
          else
            GRADLE_ARGS="$BASE_ARGS"
          fi
          echo "GRADLE_ARGS=$GRADLE_ARGS" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew $GRADLE_ARGS

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  dispatch:
    needs: [ publish_vars, build ]
    strategy:
      matrix:
        repo: ["enonic/app-admin-home", "enonic/app-applications", "enonic/app-users" ]
    runs-on: ubuntu-latest
    if: needs.publish_vars.outputs.publish == 'true'
    steps:
      - name: Workflow Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repo: ${{ matrix.repo }}
          workflow: gradle.yml

  dispatch_contentstudio:
    needs: [ publish_vars, build ]
    strategy:
      matrix:
        repo: [ "enonic/app-contentstudio" ]
    runs-on: ubuntu-latest
    if: needs.publish_vars.outputs.publish == 'true'
    steps:
      - name: Workflow Dispatch CS
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repo: ${{ matrix.repo }}
          workflow: gradle.yml
          ref: refs/heads/master
